//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratePlaylistRS500GA.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ILoadPlaylistDataService")]
    public interface ILoadPlaylistDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoadPlaylistDataService/sendLibrary", ReplyAction="http://tempuri.org/ILoadPlaylistDataService/sendLibraryResponse")]
        string sendLibrary(string xmlcontent, string libraryTitle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoadPlaylistDataService/sendLibrary", ReplyAction="http://tempuri.org/ILoadPlaylistDataService/sendLibraryResponse")]
        System.Threading.Tasks.Task<string> sendLibraryAsync(string xmlcontent, string libraryTitle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoadPlaylistDataService/createLibrary", ReplyAction="http://tempuri.org/ILoadPlaylistDataService/createLibraryResponse")]
        string createLibrary(string xmlcontent, string libraryTitle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoadPlaylistDataService/createLibrary", ReplyAction="http://tempuri.org/ILoadPlaylistDataService/createLibraryResponse")]
        System.Threading.Tasks.Task<string> createLibraryAsync(string xmlcontent, string libraryTitle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoadPlaylistDataService/getSongLyrics", ReplyAction="http://tempuri.org/ILoadPlaylistDataService/getSongLyricsResponse")]
        string getSongLyrics(string song, string artist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoadPlaylistDataService/getSongLyrics", ReplyAction="http://tempuri.org/ILoadPlaylistDataService/getSongLyricsResponse")]
        System.Threading.Tasks.Task<string> getSongLyricsAsync(string song, string artist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoadPlaylistDataService/sendPlaylist", ReplyAction="http://tempuri.org/ILoadPlaylistDataService/sendPlaylistResponse")]
        string sendPlaylist(string xmlcontent, string playlistTitle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoadPlaylistDataService/sendPlaylist", ReplyAction="http://tempuri.org/ILoadPlaylistDataService/sendPlaylistResponse")]
        System.Threading.Tasks.Task<string> sendPlaylistAsync(string xmlcontent, string playlistTitle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoadPlaylistDataService/generatePlaylist", ReplyAction="http://tempuri.org/ILoadPlaylistDataService/generatePlaylistResponse")]
        string generatePlaylist(string xmlcontent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoadPlaylistDataService/generatePlaylist", ReplyAction="http://tempuri.org/ILoadPlaylistDataService/generatePlaylistResponse")]
        System.Threading.Tasks.Task<string> generatePlaylistAsync(string xmlcontent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoadPlaylistDataService/getSimilarArtistsLF", ReplyAction="http://tempuri.org/ILoadPlaylistDataService/getSimilarArtistsLFResponse")]
        string getSimilarArtistsLF(string limit, string artist, bool doAutocorrect, string mbid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoadPlaylistDataService/getSimilarArtistsLF", ReplyAction="http://tempuri.org/ILoadPlaylistDataService/getSimilarArtistsLFResponse")]
        System.Threading.Tasks.Task<string> getSimilarArtistsLFAsync(string limit, string artist, bool doAutocorrect, string mbid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoadPlaylistDataService/getSimilarTracksLF", ReplyAction="http://tempuri.org/ILoadPlaylistDataService/getSimilarTracksLFResponse")]
        string getSimilarTracksLF(string track, string artistName, string mbid, bool doAutocorrect, string limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoadPlaylistDataService/getSimilarTracksLF", ReplyAction="http://tempuri.org/ILoadPlaylistDataService/getSimilarTracksLFResponse")]
        System.Threading.Tasks.Task<string> getSimilarTracksLFAsync(string track, string artistName, string mbid, bool doAutocorrect, string limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoadPlaylistDataService/createPlaylistLF", ReplyAction="http://tempuri.org/ILoadPlaylistDataService/createPlaylistLFResponse")]
        string createPlaylistLF(string title, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoadPlaylistDataService/createPlaylistLF", ReplyAction="http://tempuri.org/ILoadPlaylistDataService/createPlaylistLFResponse")]
        System.Threading.Tasks.Task<string> createPlaylistLFAsync(string title, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoadPlaylistDataService/updateAllRs500GaAlbumsInfo", ReplyAction="http://tempuri.org/ILoadPlaylistDataService/updateAllRs500GaAlbumsInfoResponse")]
        string updateAllRs500GaAlbumsInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoadPlaylistDataService/updateAllRs500GaAlbumsInfo", ReplyAction="http://tempuri.org/ILoadPlaylistDataService/updateAllRs500GaAlbumsInfoResponse")]
        System.Threading.Tasks.Task<string> updateAllRs500GaAlbumsInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoadPlaylistDataService/updateAllRs500GaTracksInfo", ReplyAction="http://tempuri.org/ILoadPlaylistDataService/updateAllRs500GaTracksInfoResponse")]
        string updateAllRs500GaTracksInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoadPlaylistDataService/updateAllRs500GaTracksInfo", ReplyAction="http://tempuri.org/ILoadPlaylistDataService/updateAllRs500GaTracksInfoResponse")]
        System.Threading.Tasks.Task<string> updateAllRs500GaTracksInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoadPlaylistDataService/updateAllRs500GaTrackSimilars", ReplyAction="http://tempuri.org/ILoadPlaylistDataService/updateAllRs500GaTrackSimilarsResponse" +
            "")]
        string updateAllRs500GaTrackSimilars();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoadPlaylistDataService/updateAllRs500GaTrackSimilars", ReplyAction="http://tempuri.org/ILoadPlaylistDataService/updateAllRs500GaTrackSimilarsResponse" +
            "")]
        System.Threading.Tasks.Task<string> updateAllRs500GaTrackSimilarsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoadPlaylistDataService/updateAllRs500GaArtistSimilars", ReplyAction="http://tempuri.org/ILoadPlaylistDataService/updateAllRs500GaArtistSimilarsRespons" +
            "e")]
        string updateAllRs500GaArtistSimilars();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoadPlaylistDataService/updateAllRs500GaArtistSimilars", ReplyAction="http://tempuri.org/ILoadPlaylistDataService/updateAllRs500GaArtistSimilarsRespons" +
            "e")]
        System.Threading.Tasks.Task<string> updateAllRs500GaArtistSimilarsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoadPlaylistDataService/updateAllRs500GaTracksGraphConnection" +
            "s", ReplyAction="http://tempuri.org/ILoadPlaylistDataService/updateAllRs500GaTracksGraphConnection" +
            "sResponse")]
        string updateAllRs500GaTracksGraphConnections();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoadPlaylistDataService/updateAllRs500GaTracksGraphConnection" +
            "s", ReplyAction="http://tempuri.org/ILoadPlaylistDataService/updateAllRs500GaTracksGraphConnection" +
            "sResponse")]
        System.Threading.Tasks.Task<string> updateAllRs500GaTracksGraphConnectionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoadPlaylistDataService/updateAllRs500GaArtistsGraphConnectio" +
            "ns", ReplyAction="http://tempuri.org/ILoadPlaylistDataService/updateAllRs500GaArtistsGraphConnectio" +
            "nsResponse")]
        string updateAllRs500GaArtistsGraphConnections();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoadPlaylistDataService/updateAllRs500GaArtistsGraphConnectio" +
            "ns", ReplyAction="http://tempuri.org/ILoadPlaylistDataService/updateAllRs500GaArtistsGraphConnectio" +
            "nsResponse")]
        System.Threading.Tasks.Task<string> updateAllRs500GaArtistsGraphConnectionsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoadPlaylistDataServiceChannel : GeneratePlaylistRS500GA.ServiceReference1.ILoadPlaylistDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoadPlaylistDataServiceClient : System.ServiceModel.ClientBase<GeneratePlaylistRS500GA.ServiceReference1.ILoadPlaylistDataService>, GeneratePlaylistRS500GA.ServiceReference1.ILoadPlaylistDataService {
        
        public LoadPlaylistDataServiceClient() {
        }
        
        public LoadPlaylistDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoadPlaylistDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoadPlaylistDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoadPlaylistDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string sendLibrary(string xmlcontent, string libraryTitle) {
            return base.Channel.sendLibrary(xmlcontent, libraryTitle);
        }
        
        public System.Threading.Tasks.Task<string> sendLibraryAsync(string xmlcontent, string libraryTitle) {
            return base.Channel.sendLibraryAsync(xmlcontent, libraryTitle);
        }
        
        public string createLibrary(string xmlcontent, string libraryTitle) {
            return base.Channel.createLibrary(xmlcontent, libraryTitle);
        }
        
        public System.Threading.Tasks.Task<string> createLibraryAsync(string xmlcontent, string libraryTitle) {
            return base.Channel.createLibraryAsync(xmlcontent, libraryTitle);
        }
        
        public string getSongLyrics(string song, string artist) {
            return base.Channel.getSongLyrics(song, artist);
        }
        
        public System.Threading.Tasks.Task<string> getSongLyricsAsync(string song, string artist) {
            return base.Channel.getSongLyricsAsync(song, artist);
        }
        
        public string sendPlaylist(string xmlcontent, string playlistTitle) {
            return base.Channel.sendPlaylist(xmlcontent, playlistTitle);
        }
        
        public System.Threading.Tasks.Task<string> sendPlaylistAsync(string xmlcontent, string playlistTitle) {
            return base.Channel.sendPlaylistAsync(xmlcontent, playlistTitle);
        }
        
        public string generatePlaylist(string xmlcontent) {
            return base.Channel.generatePlaylist(xmlcontent);
        }
        
        public System.Threading.Tasks.Task<string> generatePlaylistAsync(string xmlcontent) {
            return base.Channel.generatePlaylistAsync(xmlcontent);
        }
        
        public string getSimilarArtistsLF(string limit, string artist, bool doAutocorrect, string mbid) {
            return base.Channel.getSimilarArtistsLF(limit, artist, doAutocorrect, mbid);
        }
        
        public System.Threading.Tasks.Task<string> getSimilarArtistsLFAsync(string limit, string artist, bool doAutocorrect, string mbid) {
            return base.Channel.getSimilarArtistsLFAsync(limit, artist, doAutocorrect, mbid);
        }
        
        public string getSimilarTracksLF(string track, string artistName, string mbid, bool doAutocorrect, string limit) {
            return base.Channel.getSimilarTracksLF(track, artistName, mbid, doAutocorrect, limit);
        }
        
        public System.Threading.Tasks.Task<string> getSimilarTracksLFAsync(string track, string artistName, string mbid, bool doAutocorrect, string limit) {
            return base.Channel.getSimilarTracksLFAsync(track, artistName, mbid, doAutocorrect, limit);
        }
        
        public string createPlaylistLF(string title, string description) {
            return base.Channel.createPlaylistLF(title, description);
        }
        
        public System.Threading.Tasks.Task<string> createPlaylistLFAsync(string title, string description) {
            return base.Channel.createPlaylistLFAsync(title, description);
        }
        
        public string updateAllRs500GaAlbumsInfo() {
            return base.Channel.updateAllRs500GaAlbumsInfo();
        }
        
        public System.Threading.Tasks.Task<string> updateAllRs500GaAlbumsInfoAsync() {
            return base.Channel.updateAllRs500GaAlbumsInfoAsync();
        }
        
        public string updateAllRs500GaTracksInfo() {
            return base.Channel.updateAllRs500GaTracksInfo();
        }
        
        public System.Threading.Tasks.Task<string> updateAllRs500GaTracksInfoAsync() {
            return base.Channel.updateAllRs500GaTracksInfoAsync();
        }
        
        public string updateAllRs500GaTrackSimilars() {
            return base.Channel.updateAllRs500GaTrackSimilars();
        }
        
        public System.Threading.Tasks.Task<string> updateAllRs500GaTrackSimilarsAsync() {
            return base.Channel.updateAllRs500GaTrackSimilarsAsync();
        }
        
        public string updateAllRs500GaArtistSimilars() {
            return base.Channel.updateAllRs500GaArtistSimilars();
        }
        
        public System.Threading.Tasks.Task<string> updateAllRs500GaArtistSimilarsAsync() {
            return base.Channel.updateAllRs500GaArtistSimilarsAsync();
        }
        
        public string updateAllRs500GaTracksGraphConnections() {
            return base.Channel.updateAllRs500GaTracksGraphConnections();
        }
        
        public System.Threading.Tasks.Task<string> updateAllRs500GaTracksGraphConnectionsAsync() {
            return base.Channel.updateAllRs500GaTracksGraphConnectionsAsync();
        }
        
        public string updateAllRs500GaArtistsGraphConnections() {
            return base.Channel.updateAllRs500GaArtistsGraphConnections();
        }
        
        public System.Threading.Tasks.Task<string> updateAllRs500GaArtistsGraphConnectionsAsync() {
            return base.Channel.updateAllRs500GaArtistsGraphConnectionsAsync();
        }
    }
}
